# -*- coding: utf-8 -*-
"""Smart Medical Question Answering System using LoRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPyDVOPZusrFobd6SFe_qjpjoYT5wCip
"""

!pip install -q transformers datasets peft accelerate bitsandbytes sentencepiece

!pip uninstall -y torchao
!pip install -U peft transformers accelerate bitsandbytes

from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto"
)

print("Model Loaded Successfully!")

def count_parameters(model):
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(
        p.numel() for p in model.parameters()
        if p.requires_grad
    )

    print(f"Total Parameters      : {total_params:,}")
    print(f"Trainable Parameters  : {trainable_params:,}")

count_parameters(model)

from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)

print("LoRA Applied Successfully!")

def print_trainable_parameters(model):

    total_params = sum(
        p.numel() for p in model.parameters()
    )

    trainable_params = sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )

    percentage = 100 * trainable_params / total_params

    print(f"Total Parameters      : {total_params:,}")
    print(f"Trainable Parameters  : {trainable_params:,}")
    print(f"Trainable Percentage  : {percentage:.4f}%")

print_trainable_parameters(model)

from datasets import Dataset

data = {
    "question": [
        "What is diabetes?",
        "How to treat a common cold?",
        "What are the symptoms of hypertension?"
    ],

    "answer": [
        "Diabetes is a chronic disease where the body cannot regulate blood sugar properly.",
        "Rest, hydration, and over-the-counter medications can help manage symptoms.",
        "Symptoms include headaches, shortness of breath, and nosebleeds."
    ]
}

dataset = Dataset.from_dict(data)

dataset

def format_example(example):

    text = f"""
Question: {example['question']}

Answer: {example['answer']}
"""

    return {"text": text}

dataset = dataset.map(format_example)

def tokenize_function(examples):

    tokens = tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

    tokens["labels"] = tokens["input_ids"].copy()

    return tokens

tokenized_dataset = dataset.map(tokenize_function)

print("Input IDs:")
print(tokenized_dataset[0]["input_ids"])

print("\nAttention Mask:")
print(tokenized_dataset[0]["attention_mask"])

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./medical_lora",
    num_train_epochs=5,
    per_device_train_batch_size=2,
    logging_steps=1,
    save_strategy="epoch",
    learning_rate=2e-4,
    fp16=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset
)

trainer.train()

model.save_pretrained("medical_lora_adapter")

tokenizer.save_pretrained("medical_lora_adapter")

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model=model.base_model,
    tokenizer=tokenizer
)

prompt = "Question: What is diabetes?\nAnswer:"

result = generator(
    prompt,
    max_new_tokens=50
)

print(result[0]["generated_text"])

from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto"
)

medical_model = PeftModel.from_pretrained(
    base_model,
    "medical_lora_adapter"
)

input_text = """
Question: What is diabetes?

Answer:
"""

inputs = tokenizer(
    input_text,
    return_tensors="pt"
).to(medical_model.device)

outputs = medical_model.generate(
    **inputs,
    max_new_tokens=80,
    temperature=0.7
)

response = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(response)

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load base model
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

# Load LoRA adapter
model = PeftModel.from_pretrained(
    base_model,
    "medical_lora_adapter"
)

print("Medical QA Model Loaded Successfully!")

def medical_qa(question):

    prompt = f"""
You are a medical assistant.

Question: {question}

Answer:
"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        temperature=0.7,
        do_sample=True,
        top_p=0.9
    )

    answer = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    return answer

question = input("Enter your medical question: ")

response = medical_qa(question)

print("\nGenerated Answer:\n")
print(response)

def medical_qa(question):

    prompt = f"Question: {question}\nAnswer:"

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=80,
        temperature=0.7,
        do_sample=True
    )

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    answer = response.split("Answer:")[-1].strip()

    return answer


while True:

    question = input("\nAsk a medical question (type exit to stop): ")

    if question.lower() == "exit":
        break

    answer = medical_qa(question)

    print("\nMedical Assistant:")
    print(answer)